# This is the base image for creating our image
FROM ubuntu:latest

# This is changing the directory we are in
WORKDIR /home/ubuntu


# This is executed when we run the container built from this Dockerfile
CMD ["sh", "-c", "echo 'Initializing quantum flux capacitors...'; sleep 3; echo 'Synchronizing temporal nodes...'; sleep 2; echo 'Calculating pi to the last digit...'; sleep 5; echo 'Task completed successfully. Doing nothing.'; tail -f /dev/null"]